DROP TABLE IF EXISTS bios;

CREATE TABLE bios(
    id SERIAL PRIMARY KEY,
    bio VARCHAR(500) NOT NULL,
    user_id INTEGER NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
